name: flutter_application_1_workspace
description: A monorepo workspace for Flutter applications

environment:
  sdk: ^3.9.0

workspace:
  - packages/common
  - packages/counter_app
  - packages/multi_counter_app
  - packages/todo_app

dev_dependencies:
  melos: ^7.0.0
